version: '3.8'

services:
  api:
    build:
      context: ./backend-dotnet
      dockerfile: Dockerfile
    container_name: pilates_api
    environment:
      # Bu değer Dokploy panelindeki Environment Variables kısmından ezilebilir
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Database=pilates_db;Username=postgres;Password=password
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: pilates_frontend
    ports:
      - "8081:80"
    depends_on:
      - api
